# Generated by Django 5.1.5 on 2025-01-30 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_alert_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disaster_Record',
        ),
    ]
