# Generated by Django 5.1.5 on 2025-01-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_alert_app', '0004_disasterdata_userdata_delete_userlocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisasterData',
            new_name='Disaster',
        ),
    ]
